# <font color='red'> *INTERMEDIATE LEVEL* </font> 
## <font color='red'> FUNCTIONS, FILTERS AND LAMBDA EXPRESSIONS  </font> 

# <font color='blue'> 1. WRITE A FUNCTION THAT TAKES A VARIABLE AND SQUARE IT, THEN TEST THE FUNCTION BY TAKING AN INPUT FROM A USER

In [9]:
def squared(x):
    return (x*x)


In [10]:
a = int(input("Enter a number"))
print("The square of {} is {}".format(a, squared(a)))

Enter a number5
The square of 5 is 25


# <font color='blue'> 2. WRITE A FUNCTION THAT TAKES 2 VARIABLES FROM THE USER AND OBTAIN THE SUMMATION AND MULTIPLICATION, THEN TEST THE FUNCTION BY TAKING AN INPUT FROM A USER (REPEAT USING LAMBDA EXPRESSIONS)

In [57]:
def sum_multiply(x, y):
    summation = x + y
    multiply  = x * y

    return(summation, multiply)

In [58]:
a = int(input("Enter any integer number: "))
b = int(input("Enter another integer number: "))
result_sum, result_multiply = sum_multiply(a, b)

print('Multiplication = {}, addition = {}'.format(result_multiply, result_sum))

Enter any integer number: 3
Enter another integer number: 4
Multiplication = 12, addition = 7


In [ ]:
a = int(input("Enter any integer number: "))
b = int(input("Enter another integer number: "))

summation = lambda x, y: x + y
multiply = lambda x, y: x * y

print('Multiplication = {}, addition = {}'.format(summation(3,4) , multiply(3, 4)))


#  <font color='blue'>3. WRITE A FUNCTION THAT TAKES A VARIABLE AND RETURNS ITS FACTORIAL </font> 

In [11]:
def factorial(x):
    if x == 0:
        return 1
    return x * factorial(x - 1)


a = int(input("Enter a number"))
print("The factorial of {} is {}".format(a, factorial(a)))

Enter a number4
The factorial of 4 is 24


# <font color='blue'> 4. DEVELOP A SCIPT WHOSE ITEMS ARE SQUARES OF THE ORIGINAL LIST </font> 

In [32]:
my_list = range(1, 21)
print([ x ** 2 for x in my_list])

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]


# <font color='blue'> 5. WRITE A FUNCTION THAT SQUARES A VARIABLE AND THEN APPLY THE FUNCTION TO A LIST OF INTEGER NUMBERS RANING FROM -20 to 20

In [1]:
def squared(x):
    return (x*x)

numbers = range(-20, 21)
numbers_squared = list(map(lambda x: squared(x), numbers))
print(numbers_squared)

[400, 361, 324, 289, 256, 225, 196, 169, 144, 121, 100, 81, 64, 49, 36, 25, 16, 9, 4, 1, 0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]


# <font color='blue'> 6. WRITE 3 FUNCTIONS THAT TAKE THE RADIUS OF A CIRCLE AND RETURN THE DIAMETER, AREA AND CIRCUMFERENCE, TEST THE FUNCTION USING AN INPUT FROM A USER 

In [36]:
import math 

def circle_diameter(radius):
    return 2 * radius       

def circle_area(radius):
    return math.pi * radius**2   

def circle_circumference(radius):
    return 2 * math.pi * radius        



circle diameter: 10
circle area: 78.53981633974483
circle circumference: 31.41592653589793


In [37]:
r = int(input("Enter a radius of a circle"))
print('circle diameter:', circle_diameter(r))
print('circle area:', circle_area(r))
print('circle circumference:', circle_circumference(r))



Enter a radius of a circle4
circle diameter: 8
circle area: 50.26548245743669
circle circumference: 25.132741228718345


# <font color='blue'> 7. WRITE A CODE THAT TAKES A RANGE FROM A USER (UPPER AND LOWER BOUND) AND RETURNS A LIST OF POSITIVE AND EVEN NUMBERS ONLY

In [56]:
min = int(input("Enter a number (lower bound) *must be negative* : "))
max = int(input("Enter a number (Upper bound: "))

numbers = range(min, max)
greater_than_zero = list(filter(lambda x: (x > 0 and x%2==0), numbers))
print(greater_than_zero)


Enter a number (lower bound) *must be negative* : -30
Enter a number (Upper bound: 50
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]


# <font color='blue'> 8. USING FILTER AND LAMBDA EXPRESSION, WRITE A CODE THAT TAKES A LIST OF NUMBERS BELOW AND RETURNS EVEN NUMBERS ONLY

In [39]:
numbers = [6, 17, 55, 22, 120, 59, 220, 200, 1]

# filter creates a list of elements for which a function returns true
even = list(filter(lambda x: (x % 2 == 0), numbers))

print("Numbers divisible by 2 are", even)

Numbers divisible by 2 are [6, 22, 120, 220, 200]


# <font color='blue'> 9. WRITE A FUNCTION THAT TAKES TWO NUMPY MATRICES AND RETURN THE ADDITION, SUBTRACTION, TRANSPOSE, PRODUCT, DOT PRODUCT

In [40]:
def matrix_operations(a, b):
  
    print ("Matrices Addition = \n", np.add(a, b)) 
  
    print ("Matrices Subtraction = \n", np.subtract(a, b)) 
  
    print ("Matrices Multiplication = \n", np.divide(a, b)) 

    print ("Matrix A Transpose = \n", a.T) 
    
    print ("Matrix B Transpose = \n", b.T) 

    print ("Element by element multiplication = \n", np.multiply(a,b)) 

    print ("Matrices Product = \n", np.dot(a,b)) 

    print ("Element by element square root = \n", np.sqrt(a)) 

    print ("Summation of all matrix elements A = \n", np.sum(a))  
    
    print ("Summation of all matrix elements B = \n", np.sum(b)) 

    print ("Column wise summation of matrix A = \n ", np.sum(a, axis = 0)) 
  
    print ("Row wise summation of matrix A = \n", np.sum(a, axis = 1)) 

In [28]:
import numpy as np
x = np.array([[3, 9], 
                 [8, 5]]) 
y = np.array([[2, 3], 
                 [1, 7]]) 
matrix_operations(x, y)

Matrices Addition = 
 [[ 5 12]
 [ 9 12]]
Matrices Subtraction = 
 [[ 1  6]
 [ 7 -2]]
Matrices Multiplication = 
 [[1.5        3.        ]
 [8.         0.71428571]]
Matrix A Transpose = 
 [[3 8]
 [9 5]]
Matrix B Transpose = 
 [[2 1]
 [3 7]]
Element by element multiplication = 
 [[ 6 27]
 [ 8 35]]
Matrices Product = 
 [[15 72]
 [21 59]]
Element by element square root = 
 [[1.73205081 3.        ]
 [2.82842712 2.23606798]]
Summation of all matrix elements A = 
 25
Summation of all matrix elements B = 
 13
Column wise summation of matrix A = 
  [11 14]
Row wise summation of matrix A = 
 [12 13]


# <font color='blue'> 10. WRITE A FUNCTION THAT TAKES TWO VALUES FORM A USER AND SUM THEM UP. IF NO VALUES ARE PROVIDED, ASSUME DEFAULT VALUES OF 3 AND 5

In [42]:
def summation(x=4, y=5):
    return x + y

summation(5, 7)

summation()

9

# <font color='blue'> 11. WRITE A SCRIPT THAT WILL PROMPT A USER FOR A RANGE (MIN/MAX VALUE) AND RETURNS NUMBERS THAT ARE DIVISIBLE BY 4 BUT ARE NOT MULTIPLES OF 3 

In [ ]:
min = int(input("Enter min range (window of numbers to look for!): "))
max = int(input("Enter max range: "))

my_numbers =[]
for i in range(min, max):
    if (i%4==0) and (i%3!=0):
        my_numbers.append(str(i))
print(my_numbers)

# <font color='blue'> 12. DEFINE AN ENGLISH TO FRENCH TRANSLATOR FUNCTION THAT TAKES AN INPUT FROM A USER AND RETURNS THE TRANSLATION, USE ANY 5 KNOWN WORDS

In [69]:
eng_french = {'happy': 'heureux', 
             'success': 'Succès', 
             'studying': 'en train d\'étudier',
             'traveling': 'en voyageant',
             'love': 'amour'}

def dictionary_English2Frensh(word):
    try:
        return eng_french[word]
    except KeyError:
        return "Dictionary does not contain this word"


In [71]:
word = input("Enter a word in english: ").lower()
print(dictionary_English2Frensh(word))


Enter a word in english: HAPPY
heureux


# NOW YOU SHOULD BE FAMILIAR WITH FUNCTIONS, GREAT JOB!